### PR TITLE
Lhw828 master 462

### PR DESCRIPTION
**Pull request by stumbles**

### CODE REVIEW

**Comment by stumbles** [comment]
Compile fine here now. Guessing CI gcc it too old.

**Comment by esselfe** [comment]
Fails with:

BasicTaskScheduler.cpp: In member function 'virtual void BasicTaskScheduler::SingleStep(unsigned int)':
BasicTaskScheduler.cpp:191:40: error: 'struct std::atomic_flag' has no member named 'test'
  191 |       if (fTriggersAwaitingHandling[i].test()) {
      |                                        ^~~~
make[1]: *** [Makefile:41: BasicTaskScheduler.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/usr/src/live/BasicUsageEnvironment'
make: *** [Makefile:41: all] Error 2

**Comment by esselfe** [comment]
Works with gcc 12.1.0
